services:
  postgres:
    image: postgres:16
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: reviews_db
    ports:
        - "5432:5432"
    volumes:
        - pgres_data:/var/lib/postgresql/data
  api:
    build: .
    command: npm start
    ports:
      - "80:80"
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  pgres_data: